// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/jaeyoung0509/todo/ent/schema"
	"github.com/jaeyoung0509/todo/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTask is the schema descriptor for task field.
	todoDescTask := todoFields[0].Descriptor()
	// todo.TaskValidator is a validator for the "task" field. It is called by the builders before save.
	todo.TaskValidator = todoDescTask.Validators[0].(func(string) error)
	// todoDescDone is the schema descriptor for done field.
	todoDescDone := todoFields[1].Descriptor()
	// todo.DefaultDone holds the default value on creation for the done field.
	todo.DefaultDone = todoDescDone.Default.(bool)
}
